name: try_on
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.1.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  http: 1.3.0

  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/
    - assets/logos/
    - assets/images/animations/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/reviews/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica_regular.otf
        - asset: assets/fonts/coolvetica_regular_italic.otf
          style: italic

